package com.gsk.sia.similarity.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 16 09:04:59 EST 2024]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class EventLogPeerImpl
    extends com.gsk.sia.similarity.om.BaseEventLogPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1708092299081L;



}
