
package com.gsk.sia.similarity.om;


import java.util.ArrayList;
// jdk
import java.util.List;
import java.util.Vector;

import org.apache.torque.criteria.Criteria;
// Torque
import org.apache.torque.om.Persistent;
import org.apache.torque.util.CountHelper;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Jun 11 12:41:46 EDT 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class EventLog
    extends com.gsk.sia.similarity.om.BaseEventLog
    implements Persistent
{
   /**
     * return list of all logs sort from newest to oldest
     */
    public static List getAllLogs()
    {
        try {
            Criteria criteria = new Criteria();
            criteria.addAscendingOrderByColumn(EventLogPeer.TX_DATE);
            List results = EventLogPeer.doSelect(criteria);
            return results;
        }
        catch (Exception e) {
            // Log.info("No logs found.");
            return null;
        }
    }
    
    
    /**
     * Get the event logs using pagination method
     */
    public static List<EventLog> getAllLogs(int limit, int idx)
    {
    	// int limit = 5;
    	List<EventLog> events = new Vector<EventLog>();
    	List<Integer> postId = new Vector<Integer>();

    	try
    	{
    		Criteria criteria = new Criteria();
    		// Newest to oldest
    		criteria.addDescendingOrderByColumn(EventLogPeer.TX_DATE);
    		List<EventLog> history = (List<EventLog>) EventLogPeer.doSelect(criteria);

	        // Paginate the results
	        int startId = 0;
	        int endId = 0;
	        int currId = 0;

	        // Check index size
	        if ( history.size() > limit )
	        {
	        	// Set the start and end ID
	        	startId = limit * idx;
	        	endId = startId + limit;
	    		for ( EventLog h : history )
	    		{
	    			if ( startId <= currId && currId < endId )
	    			{
	    				events.add(h);
	    			}
					currId++;
	    		}

	        } else
	        {
	    		for ( EventLog h : history )
	    			events.add(h);
	        }

    		return events;
    	} catch ( Exception e ) {
    		return null;
    	}
    }
    
    
    /**
     * Determine number of pages to show the posts
     * @param product_key
     * @return
     */
    public static List<Integer> getEventPages(int limit)
    {
    	
		try {
			Criteria criteria = new Criteria();
			criteria.where(EventLogPeer.LOG_ID, 0, Criteria.GREATER_EQUAL );

			CountHelper ch = new CountHelper();
			int count = ch.count(criteria);
			
			// convert to pages
        	List<Integer> pages = new ArrayList<>();
    		int page_count = (int) Math.ceil(count/limit) + 1;
    		for ( int i = 0; i < page_count; i++ )
    			pages.add(i+1);
    		return pages;
    	} catch ( Exception e ) {
    		return null;
    	}
    }


}
