package com.gsk.sia.similarity.om;


/**
 * Maps ResultSet rows into FaersMps objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 10 10:13:36 EDT 2024]
 *
 */
public class FaersMpsRecordMapper extends BaseFaersMpsRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1712758416205L;



}
