package com.gsk.sia.similarity.om;


/**
 * Maps ResultSet rows into FaersHierarchy objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 10 10:01:36 EDT 2024]
 *
 */
public class FaersHierarchyRecordMapper extends BaseFaersHierarchyRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1712757696526L;



}
