package com.gsk.sia.similarity.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 10 10:13:35 EDT 2024]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class FaersMps
    extends com.gsk.sia.similarity.om.BaseFaersMps
{
    /** Serial version */
    private static final long serialVersionUID = 1712758415534L;



}
