package com.gsk.sia.similarity.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Feb 22 13:47:12 EST 2024]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class FaersCodePeer
    extends com.gsk.sia.similarity.om.BaseFaersCodePeer
{

}
