package com.gsk.sia.similarity.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 10 10:42:37 EDT 2024]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class FaersMphPeerImpl
    extends com.gsk.sia.similarity.om.BaseFaersMphPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1712760157138L;



}
