package com.gsk.sia.similarity.om;


/**
 * Maps ResultSet rows into FaersMph objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 10 10:42:37 EDT 2024]
 *
 */
public class FaersMphRecordMapper extends BaseFaersMphRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1712760157420L;



}
