package com.gsk.sia.similarity.om;


/**
 * Maps ResultSet rows into FaersCode objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Feb 22 13:47:13 EST 2024]
 *
 */
public class FaersCodeRecordMapper extends BaseFaersCodeRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1708627633231L;



}
