package com.gsk.sia.similarity.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 10 10:42:37 EDT 2024]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class FaersMpgPeer
    extends com.gsk.sia.similarity.om.BaseFaersMpgPeer
{

}
