package com.gsk.sia.similarity.om;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.apache.torque.criteria.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Feb 22 13:47:12 EST 2024]
 *
 * You should add additional methods to this class to meet the application
 * requirements. This class will only be generated as long as it does not
 * already exist in the output directory.
 */

public class FaersCode extends com.gsk.sia.similarity.om.BaseFaersCode {
	/** Serial version */
	private static final long serialVersionUID = 1708627632744L;


}
