package com.gsk.sia.similarity.om;


/**
 * Maps ResultSet rows into HelpFile objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 16 09:04:59 EST 2024]
 *
 */
public class HelpFileRecordMapper extends BaseHelpFileRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1708092299257L;



}
