
package com.gsk.sia.similarity.om;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.util.List;
import java.util.Vector;

import org.apache.commons.io.FileUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.torque.om.Persistent;
import org.apache.torque.criteria.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Aug 31 13:39:55 EDT 2016]
 *
 * You should add additional methods to this class to meet the application
 * requirements. This class will only be generated as long as it does not
 * already exist in the output directory.
 */
public class HelpFile extends com.gsk.sia.similarity.om.BaseHelpFile implements Persistent {

	/** Logging */
	private static Log log = LogFactory.getLog(HelpFile.class);

	/**
	 * Get the enabled help file
	 * @return
	 */
	public static HelpFile getDefault() {
		List<HelpFile> allFiles = getAllFiles();
		for (HelpFile f : allFiles) {
			if (f.isEnabled() == true)
				return f;
		}
		return null;
	}

	/**
	 * This is our primary entry point
	 * @param report
	 * @return
	 */
	public ByteArrayOutputStream getWordDoc()
	{
		try
		{
			ByteArrayOutputStream bos = new ByteArrayOutputStream();
			bos.write(this.getDocument());
			return bos;
			
		} catch ( Exception e ) {
			log.error("error loading help file: " + e.toString());
			return null;
		}
		
	}
	
	/**
	 * There should only be one help file by default
	 */
	public void setDefault() {
		try {
			List<HelpFile> allFiles = getAllFiles();
			for (HelpFile f : allFiles) {
				if (f.getRefId() == this.getRefId()) {
					this.setEnabled(true);
					this.save();
				} else {
					f.setEnabled(false);
					f.save();
				}
			}
		} catch (Exception e) {
			log.error("Could not set help file as enabled");
		}
		return;
	}

	public static List<HelpFile> getAllFiles() {

		try {
			// List all products in alpha order
			Criteria criteria = new Criteria();
			criteria.addDescendingOrderByColumn(HelpFilePeer.MODIFIED_DATE);
			return (List<HelpFile>) HelpFilePeer.doSelect(criteria);
		} catch (Exception e) {
			return new Vector<HelpFile>();
		}
	}

	public static HelpFile getHelpFileByKey(int pid) {

		try {
			// List all drug abuse options in alpha order
			Criteria criteria = new Criteria();
			criteria.where(HelpFilePeer.REF_ID, pid);
			return (HelpFile) HelpFilePeer.doSelect(criteria).get(0);
		} catch (Exception e) {
			return null;
		}
	}

}
