package com.gsk.sia.similarity.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue May 04 18:14:04 EDT 2021]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class InsightUserPeer
    extends com.gsk.sia.similarity.om.BaseInsightUserPeer
{

}
