package com.gsk.sia.similarity.om;

import java.util.List;

// Turbine
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.fulcrum.security.torque.om.TurbineUser;
import org.apache.fulcrum.security.torque.om.TurbineUserPeer;
import org.apache.torque.criteria.Criteria;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu May 27 12:06:41 EDT 2010]
 *
 * You should add additional methods to this class to meet the application
 * requirements. This class will only be generated as long as it does not
 * already exist in the output directory.
 */
public class InsightUser extends com.gsk.sia.similarity.om.BaseInsightUser implements Persistent {
	/** Logging */
	private static Log log = LogFactory.getLog(InsightUser.class);

	public TurbineUser getTurbineUser() {
		try {
			Criteria criteria = new Criteria();
			criteria.where(TurbineUserPeer.USER_ID, this.getTurbineUserId());
			return TurbineUserPeer.doSelectSingleRecord(criteria);
		} catch (Exception e) {
			log.error("Could not locate TurbineUser for account: " + this.getUserId());
		}
		return null;
	}

	/**
	 * Lookup the insight user from database based on user login name
	 * 
	 * @param username
	 * @return
	 */
	public static InsightUser getInsightUser(String username) {
		try {
			Criteria criteria = new Criteria();
			criteria.where(TurbineUserPeer.LOGIN_NAME, username);
			TurbineUser tu = TurbineUserPeer.doSelectSingleRecord(criteria);

			criteria = new Criteria();
			criteria.where(InsightUserPeer.TURBINE_USER_ID, tu.getId());
			InsightUser user = InsightUserPeer.doSelectSingleRecord(criteria);
			if (user != null)
				return user;

		} catch (Exception e) {
			log.error("Could not locate InsightUser for username: " + username);
		}
		return null;
	}


	/**
	 * Get user name from turbine
	 * 
	 * @return
	 */
	public String getUserName() {

		try {
			Criteria c = new Criteria();
			c.where(TurbineUserPeer.USER_ID, this.getTurbineUserId());
			TurbineUser user = TurbineUserPeer.doSelectSingleRecord(c);
			return user.getEntityName();
		} catch (Exception e) {
			return null;
		}
	}

	public static InsightUser getInsightUserWithTurbineUserId(int userId) {
		try {
			Criteria criteria = new Criteria();
			criteria.where(InsightUserPeer.TURBINE_USER_ID, userId);
			return InsightUserPeer.doSelectSingleRecord(criteria);
		} catch (Exception e) {
			log.error("Could not locate TurbineUser for account: " + userId);
		}
		return null;
	}

	public static InsightUser setUser(String login) {

		// invalid users to assign too
		if (login.toLowerCase().contentEquals("anon") || login.toLowerCase().contentEquals("none"))
			return null;

		try {
			Criteria criteria = new Criteria();
			criteria.where(TurbineUserPeer.LOGIN_NAME, login);
			TurbineUser user = TurbineUserPeer.doSelectSingleRecord(criteria);
			if (user != null)
				return getInsightUserWithTurbineUserId(user.getEntityId());
		} catch (Exception e) {
		}
		return null;

	}

	/**
	 * Get all users in alpha order
	 * @return
	 */
	public static List<InsightUser> getAllUsers() {
		
		try {
			Criteria criteria = new Criteria();
			criteria.where(InsightUserPeer.TURBINE_USER_ID, 0, Criteria.GREATER_EQUAL);
			criteria.addAscendingOrderByColumn(InsightUserPeer.LAST_NAME);
			criteria.addAscendingOrderByColumn(InsightUserPeer.FIRST_NAME);
			return InsightUserPeer.doSelect(criteria);
		} catch (Exception e) {
			log.error("Could not retrieve user list: " + e.toString());
			return null;
		}
	}

}
