package com.gsk.sia.similarity.om;


/**
 * Maps ResultSet rows into MeddraSmqCode objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Feb 22 10:11:06 EST 2024]
 *
 */
public class MeddraSmqCodeRecordMapper extends BaseMeddraSmqCodeRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1708614666393L;



}
