
package com.gsk.sia.similarity.om;


import org.apache.torque.criteria.Criteria;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Jun 10 12:44:01 EDT 2015]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class MeddraCodeType
    extends com.gsk.sia.similarity.om.BaseMeddraCodeType
    implements Persistent
{

	/**
	 * Get the code type object for a particular TTY
	 * @param tty
	 * @return
	 */
	public static MeddraCodeType getCodeType(String tty) {
		try {
			Criteria criteria = new Criteria();
			criteria.where(MeddraCodeTypePeer.CODE_TYPE, tty);
			return MeddraCodeTypePeer.doSelectSingleRecord(criteria);
		} catch (Exception e) {
			return null;
		}
	}
}
