package com.gsk.sia.similarity.om;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.apache.torque.criteria.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Feb 22 10:11:05 EST 2024]
 *
 * You should add additional methods to this class to meet the application
 * requirements. This class will only be generated as long as it does not
 * already exist in the output directory.
 */

public class MeddraSmq extends com.gsk.sia.similarity.om.BaseMeddraSmq {
	/** Serial version */
	private static final long serialVersionUID = 1708614665616L;

	/**
	 * Test if scope is narrow
	 * 
	 * @param scope
	 * @return
	 */
	public static boolean isNarrow(String scope) {
		if (!StringUtils.isAllEmpty(scope))
			if (scope.toLowerCase().trim().contentEquals("narrow"))
				return true;
		return false;
	}

	/**
	 * Retrieve an SQM matching the criteria
	 * 
	 * @param smqCode
	 * @param smq
	 * @param scope
	 * @return
	 */
	public static MeddraSmq getSmq(String smqCode, String smq, String scope) {

		boolean isNarrow = MeddraSmq.isNarrow(scope);
		boolean isBroad = false;
		if (isNarrow == false)
			isBroad = true;

		try {
			Criteria c = new Criteria();
			c.where(MeddraSmqPeer.NAME, smq);
			c.where(MeddraSmqPeer.CODE, smqCode);
			c.where(MeddraSmqPeer.BROAD, isBroad);
			c.where(MeddraSmqPeer.NARROW, isNarrow);
			MeddraSmq ms = MeddraSmqPeer.doSelectSingleRecord(c);
			return ms;
		} catch (Exception e) {
			return null;
		}
	}

	/**
	 * Check if an SMQ has already been added to the database s *
	 * 
	 * @param smqCode
	 * @param smq
	 * @param scope
	 * @return
	 */
	public static boolean checkSmqExists(String smqCode, String smq, String scope) {

		MeddraSmq ms = getSmq(smqCode, smq, scope);
		if (ms != null)
			return true;
		return false;
	}

	/**
	 * Set the scope parameters
	 * 
	 * @param scope
	 */
	public void setScope(String scope) {
		boolean isNarrow = MeddraSmq.isNarrow(scope);
		boolean isBroad = false;
		if (isNarrow == false)
			isBroad = true;

		// Set the scope
		this.setNarrow(isNarrow);
		this.setBroad(isBroad);
		return;

	}

	/**
	 * SMQ's should be located by just the code and scope if available
	 * 
	 * @param smqCode
	 * @param scope
	 * @return
	 */
	public static MeddraSmq getSmq(String smqCode, String scope) {
		boolean isNarrow = MeddraSmq.isNarrow(scope);
		boolean isBroad = false;
		if (isNarrow == false)
			isBroad = true;

		if (isNarrow == true) {
			try {
				Criteria c = new Criteria();
				c.where(MeddraSmqPeer.CODE, smqCode);
				c.where(MeddraSmqPeer.BROAD, false);
				c.where(MeddraSmqPeer.NARROW, true);
				MeddraSmq ms = MeddraSmqPeer.doSelectSingleRecord(c);
				return ms;
			} catch (Exception e) {
				return null;
			}
		} else {
			try {
				// Test if a broad definition exists for this SMQ
				Criteria c = new Criteria();
				c.where(MeddraSmqPeer.CODE, smqCode);
				c.where(MeddraSmqPeer.BROAD, true);
				c.where(MeddraSmqPeer.NARROW, false);
				MeddraSmq ms = MeddraSmqPeer.doSelectSingleRecord(c);
				if (ms != null) {
					return ms;
				} else {
					// If broad not found, default to narrow
					c = new Criteria();
					c.where(MeddraSmqPeer.CODE, smqCode);
					c.where(MeddraSmqPeer.BROAD, false);
					c.where(MeddraSmqPeer.NARROW, true);
					return MeddraSmqPeer.doSelectSingleRecord(c);
				}
			} catch (Exception e) {
				return null;
			}
		}
	}

	/**
	 * Get the meddra codes linked to the SMQ
	 * 
	 * @return
	 */
	public List<MeddraCode> getMeddraCodes(boolean ptOnly) {
		List<MeddraCode> codes = new ArrayList<>();
		try {
			// Link the Meddra Codes that belong to this SMQ
			Criteria c = new Criteria();
			c.where(MeddraSmqCodePeer.SMQ_ID, this.getRefId());
			c.addJoin(MeddraSmqCodePeer.CODE_ID, MeddraCodePeer.REF_ID);
			
			// Restrict to only PT level codes
			if ( ptOnly == true )
			{
				c.addJoin(MeddraCodePeer.CODE_ID, MeddraCodeTypePeer.REF_ID);
				c.where(MeddraCodeTypePeer.CODE_TYPE, "PT", Criteria.EQUAL);
			}
			
			codes = (List<MeddraCode>) MeddraCodePeer.doSelect(c);
		} catch (Exception e) {
			return null;
		}

		return codes;

	}

	/**
	 * Get all SMQs from database
	 * @return
	 */
	public static List<MeddraSmq> getAllSmqs() {
		try {
			Criteria c = new Criteria();
			c.addAscendingOrderByColumn(MeddraSmqPeer.CODE);
			List<MeddraSmq> results = MeddraSmqPeer.doSelect(c);
			return results;
		} catch (Exception e) {
			return null;
		}
	}

}
