package com.gsk.sia.similarity.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Feb 22 10:11:06 EST 2024]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class MeddraSmqPeer
    extends com.gsk.sia.similarity.om.BaseMeddraSmqPeer
{

}
