package com.gsk.sia.similarity.om;


/**
 * Maps ResultSet rows into MeddraVersion objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue May 04 18:14:04 EDT 2021]
 *
 */
public class MeddraVersionRecordMapper extends BaseMeddraVersionRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1620166444924L;



}
