package com.gsk.sia.similarity.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Apr 12 15:57:55 EDT 2024]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class MeddraLltPtMapPeerImpl
    extends com.gsk.sia.similarity.om.BaseMeddraLltPtMapPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1712951875440L;



}
