package com.gsk.sia.similarity.om;


/**
 * Maps ResultSet rows into MeddraLltPtMap objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Apr 12 15:57:55 EDT 2024]
 *
 */
public class MeddraLltPtMapRecordMapper extends BaseMeddraLltPtMapRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1712951875709L;



}
