package com.gsk.sia.similarity.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Feb 22 10:11:06 EST 2024]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class MeddraSmqCodePeerImpl
    extends com.gsk.sia.similarity.om.BaseMeddraSmqCodePeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1708614666097L;



}
