package com.gsk.sia.similarity.om;


/**
 * Maps ResultSet rows into TurbineRole objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue May 04 16:05:02 EDT 2021]
 *
 */
public class TurbineRoleRecordMapper extends BaseTurbineRoleRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1620158702732L;



}
