package com.gsk.sia.similarity.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue May 04 16:05:02 EDT 2021]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class TurbinePermission
    extends com.gsk.sia.similarity.om.BaseTurbinePermission
    implements org.apache.fulcrum.security.model.turbine.entity.TurbinePermission
{
    /** Serial version */
    private static final long serialVersionUID = 1620158702243L;



}
